---
project_name: "train_resnet18_cifar100"
wandb_name: "wandb_train_resnet18_cifar100"

model:
  name: "TorchvisionClassifier"
  kwargs:
    arch_name: "resnet50"
    num_classes: 100
    resolution: 32
    weights: "DEFAULT"

optimization:
  optimizer: SGD
  optimizer_params: 
    lr: 0.01
  lr_scheduler: "StepLR"
  lr_scheduler_params:
    step_size: 15
    gamma: 0.2

accelerator:
  log_with: wandb

train:
# trainer params
  validation_interval: 1
  save_train_status_interval: 10
  loss_fn: "cross_entropy"
  seed: 0
# data params
  dataset_path: "../../../../datasets/cifar100"
  train_transforms: 
    RandomHorizontalFlip:
      p: 0.5
    ToTensor: null
  val_transforms: 
    ToTensor: null
  train_batch_size: 128
  val_batch_size: 128
  num_workers: 4
# train function
  epochs: 50