---
project_name: "train_resnet18_cifar100"
wandb_name: "wandb_train_resnet18_cifar100"

model:
  name: "TorchvisionClassifier"
  kwargs:
    arch_name: "resnet50"
    num_classes: 100
    resolution: 32
    weights: "DEFAULT"

optimization:
  optimizer: SGD
  optimizer_params: {'lr': 1e-2}
  lr_scheduler: "StepLR"
  lr_scheduler_params: {'step_size': 50, 'gamma': 0.25}

accelerator:
  null

train:
# trainer params
  validation_interval: 1
  save_train_status_interval: 10
  loss_fn: cross_entropy"
  seed: 0
# data params
  dataset_path: "../../../../datasets/cifar100"
  train_batch_size: 128
  val_batch_size: 128
  num_workers: 4
# train function
  epochs: 100